### ISSUE TITLE
Quotes for *every* String in a CSV with a schema from a POJO

### ISSUE THREAD

**Issue by DerName** [FasterXML/jackson-dataformat-csv#111]
hi,

how can I configure a schema to use a QuoteChar for every string column in csv file?

thanks

Michael

**Comment by cowtowncoder** [comment]
@DerName Please use `jackson-users` google group for asking usage questions.

But for this specific question: yes, enable `CsvGenerator.Feature.ALWAYS_QUOTE_STRINGS` (either via `CsvFactory` or mapper).
