### ISSUE TITLE
readerFor method not implemented

### ISSUE THREAD

**Issue by robinbansal240611** [FasterXML/jackson-dataformat-csv#123]
Method "readerFor" is not implemented in the jar.

**Comment by cowtowncoder** [comment]
@robinbansal240611 Huh? Which version? What happens? Are you sure you are using same minor version of CSV module and `jackson-databind`?

**Comment by robinbansal240611** [comment]
Hi Tatu,

Apologies, as I forgot to reply your email. It was my bad I didn't use the
right version. It think you could also mention other versions to use that
will help other persons to understand it clearly.

Thanks for the quick reply on that issue.

Regards,
Robin Bansal

**Comment by cowtowncoder** [comment]
Glad that you were able to resolve this.

I don't know which versions you had problems with, but the general rule is that versions of Jackson components must match each other's minor versions. Patch levels do not have to match.
Sometimes adjacent minor versions also work, but given that it is not possible to easily document combinations it is safest to try to make them match.
