### ISSUE TITLE
LocalDateTime and com.fasterxml.jackson.databind.JsonMappingException: CSV generator does not support Object values for properties 

### ISSUE THREAD

**Issue by hexmind** [FasterXML/jackson-dataformat-csv#135]
How to write LocalDateTime to CSV (as String date)? 
@JsonUnwrapped isn't solution.

**Comment by cowtowncoder** [comment]
@hexmind please use mailing lists for usage questions in future.

But as to your problem: make sure enable writing of values as Strings. Couple of ways; either using  `@JsonFormat`

```java
@JsonFormat(shape=JsonFormat.Shape.STRING)
```

or by global setting

```java
mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
```
