### ISSUE TITLE
Allow to use multiple-characters delimiter to separate column: withColumnSeparator

### ISSUE THREAD

**Issue by jefferyyuan** [FasterXML/jackson-dataformat-csv#141]
It's common that we use multiple-characters delimiter to separate columns in CVS: such as: [|]
Sometimes, we have no choice as third-party defines the csv format like that.

Sample data:
FirstName[|]LastName[|]Address
John[|]Smith[|]123 Main St.

https://github.com/FasterXML/jackson-dataformat-csv/issues/92 supports to use multiple characters as array element separator, It would be great if same can be done for withColumnSeparator.

I did some google search: seems there is no java library that supports use multiple-characters as the column separator.

But the C# CsvHelper does
https://github.com/JoshClose/CsvHelper

Thanks.

**Comment by cowtowncoder** [comment]
moved: https://github.com/FasterXML/jackson-dataformats-text/issues/14
