### ISSUE TITLE
NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.readerFor

### ISSUE THREAD

**Issue by neophd** [FasterXML/jackson-dataformat-csv#144]
Hi
I'm trying to use jackson for parse csv into pojo with following code:

`CsvSchema bootstrapSchema = CsvSchema.emptySchema().withHeader();`
`ObjectMapper mapper = new CsvMapper();`
`File csv = new File("c:\\Users\\prsousa\\Downloads\\ftp\\teste.csv");`
`MappingIterator<Pojo> it = mapper.readerFor(Pojo.class).with(bootstrapSchema).readValues(csv);`

My pom.xml has following jackson dependencies:

`<dependency>`
`	<groupId>com.fasterxml.jackson.core</groupId>`
`	<artifactId>jackson-databind</artifactId>`
`	<version>2.8.7</version>`
`</dependency>`
`<dependency>`
`	<groupId>com.fasterxml.jackson.datatype</groupId>`
`	<artifactId>jackson-datatype-jsr310</artifactId>`
`	<version>2.8.7</version>`
`</dependency>`
`<dependency>`
`	<groupId>com.fasterxml.jackson.dataformat</groupId>`
`	<artifactId>jackson-dataformat-csv</artifactId>`
`	<version>2.8.7</version>`
`</dependency>`
`<dependency>`
`	<groupId>com.fasterxml.jackson.core</groupId>`
`	<artifactId>jackson-core</artifactId>`
`	<version>2.8.7</version>`
`</dependency>`
`<dependency>`
`	<groupId>com.fasterxml.jackson.core</groupId>`
`	<artifactId>jackson-annotations</artifactId>`
`	<version>2.8.7</version>`
`</dependency>`

I have no idea because happens this. Plz, someone can help me ?

**Comment by cowtowncoder** [comment]
@neophd You have a version conflict of some kind between `jackson-dataformat-csv` and `jackson-databind`. While your pom tries to use same versions (which is correct), somehow incompatible versions are being deployed. You need to see why this occurs: with maven, `mvn dependency:tree` can show dependency graph.
