### ISSUE TITLE
Feature to ignore empty trailing lines

### ISSUE THREAD

**Issue by robmoore** [FasterXML/jackson-dataformat-csv#145]
We have a case where we're reading documents produced by a third-party which contains trailing empty lines. It appears that the reader attempts to create empty POJO entries for these lines rather than ignoring them.

**Comment by robmoore** [comment]
A work around for this is to simply read each value individually rather than using `readValues()`. Nevertheless, for the streaming case it would be nice to be able to use `readValues()`.

**Comment by cowtowncoder** [comment]
moved: https://github.com/FasterXML/jackson-dataformats-text/issues/12
