### ISSUE TITLE
Support coercion of empty strings to null objects

### ISSUE THREAD

**Issue by robmoore** [FasterXML/jackson-dataformat-csv#146]
We're working with a set of files that contains both empty strings and `NULL` values. We are using `.withNullValue("NULL")` as well as `DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT` but are ending up with empty strings rather than null values for these cases.

In issue [112](https://github.com/FasterXML/jackson-dataformat-csv/issues/112), @cowtowncoder suggested it might be possible to support an alternate notation in addition to the explicit null value indicated in `withNullValue()`.

**Comment by cowtowncoder** [comment]
Moved: https://github.com/FasterXML/jackson-dataformats-text/issues/7
