### ISSUE TITLE
Edit column name at first row

### ISSUE THREAD

**Issue by nquyhuynhwork** [FasterXML/jackson-dataformat-csv#147]
Hi,

Have any way to edit column name at first row of csv

Normal CSV:
id,name
1,AAA
2,BBB

Edited column name CSV:
ID,Fullname
1,AAA
2,BBB

Thanks

**Comment by cowtowncoder** [comment]
Please use mailing lists for usage questions: issue tracker is for reporting problems and suggesting new features:

https://groups.google.com/forum/#!forum/jackson-user
