### ISSUE TITLE
ObjectWriter.writeValues() writing out header for each call.

### ISSUE THREAD

**Issue by bhchandra** [FasterXML/jackson-dataformat-csv#148]
This is related to:  writeValue writes out header in each call. #71 which is closed.

The following was mentioned in the page.

"_But I think what you may really want to use is the new method(s) added in 2.5: ObjectWriter.writeValues() (http://fasterxml.github.io/jackson-databind/javadoc/2.5/com/fasterxml/jackson/databind/ObjectWriter.html#writeValues%28java.io.OutputStream%29).
It returns a SequenceWriter which has write and writeAll methods to use.
That should properly handle headers; and if not, that would definitely be a bug_".

I am not sure, please take a look at this code.

```
                csvMapper.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);
                fileStream = Files.newOutputStream(this.path, CREATE, WRITE, APPEND);
                jsonGenerator = csvMapper.getFactory().createGenerator(fileStream);

                //Works Good. Doesn't write header for each call
                csvMapper.writer(schema).writeValue(jsonGenerator, data);   
  
                //Writes header for each call.        
                csvMapper.writer(schema).writeValues(fileStream).write(data);
```

"_In the end use of ObjectWriter.writeValues() is the recommended method, and the proper resolution_"

I want to use writeValues() since it is the recommended.
Please resolve if I am making some mistake in code or this is a bug?
using 2.8.7.

Thanks!!

**Comment by cowtowncoder** [comment]
Due to reorganizing repo, I will move this, and then add comments.

**Comment by cowtowncoder** [comment]
Moved: https://github.com/FasterXML/jackson-dataformats-text/issues/8
