### ISSUE TITLE
CSV is not escaped property on JSON input

### ISSUE THREAD

**Issue by kancsuki** [FasterXML/jackson-dataformat-csv#149]
Hello everyone,

I'm reading a JSON object which has some **escaped characters**, such as `{"desc": "a \t b"}`. If I write it as JSON string, it is properly escaped. (It even matches the original JSON.) That's fine. However, when I'm **writing it as CSV**, it **unescapes** and **it** creates a tab character, e.g. `123,a->b` . I would like to get `123,a\\tb` as the result of the CSV export.
Am I missing something or is it a bug?

Thanks.

```java
@JsonPropertyOrder({ "id", "desc" })
public class IdDesc {

    public String id, desc;

    public static void main(String[] args) throws Exception {
        final String jsonContent = "{\"id\":\"123\",\"desc\":\"a\\tb\"}";
        final String csvContent = "123,\"a\\tb\"\n";

        ObjectMapper jsonMapper = new ObjectMapper();
        IdDesc value = jsonMapper.readValue(jsonContent, IdDesc.class); // read json with object mapper

        String outputJson = jsonMapper.writeValueAsString(value); // write json with object mapper
        System.out.println(outputJson.equals(jsonContent)); // true

        CsvMapper mapper = new CsvMapper();
        String outputCsv = mapper.writer(mapper.schemaFor(IdDesc.class))
                .writeValueAsString(value);
        System.out.println(outputCsv.equals(csvContent)); // false

        System.out.println(outputCsv); // value is '123,\"a\tb\"' istead of '123,\"a\\tb\"'
    }

}
```

**Comment by cowtowncoder** [comment]
By default tab character is legal in CSV (it's not a double-quote or separator comma), so it will be included as is. So this is not bug.
Further, CSV "standard" does not define escape character, so use of backslash (for example) would have to use custom logic that other tools may or may not support.
So by default such escaping is not possible.

Having said that... Jackson CSV module does indeed allow use of escape characters: one is to be defined via `CsvSchema`:

```java
     CsvSchema schema = mapper.schemaFor(IdDesc.class)
          .withEscapeChar('\\');
```

this is mostly to support use of escaping in existing content and will only add extra escaping for escape character itself (and quote character); there is no automatic escaping for control characters like tab currently. So: when reading, all escapes would be handled using whatever escape character you define, but no escaping beyond `\\` and `\"` would be applied.

Adding a feature to enable more thorough escaping could be considered as a new feature: there is existing type (`CharacterEscapes`) from `jackson-core` that could be used to take in configuration.
This would require changes in `CsvEncoder` but is doable.

**Comment by kancsuki** [comment]
Thanks for the quick answer. 

I tried the ˙`.withEscapeChar('\\');` version, same result. Sadly, the input JSON text is from an outside source, so I'm unable to change the JSON generation part, thus no extra escape chars. I will look into some workarounds.

The proposed feature sounds nice. **+1**

**Comment by cowtowncoder** [comment]
@kancsuki Right, as I said, encoder does not encode anything past bare minimum, only escape character itself (and quote). So ability mostly helps in decoding escaped characters.

I did realize one other challenge, for what it is worth: while escaping works ok with "regular" characters (just prepend escape character), there is also no standard for control codes: although `\t` is commonly used, there isn't anything to fully define this as tab in context of CSV.
`CharacterEscapes` can define whatever translation is needed, of course, but when decoding there is no counterpart, and by default rules, `\t` would simply become `t` character.

So I am not sure how good this solution would be. It would be possible to add a flag of some kind to indicate "use standard Unix backslash escapings" but... this can quickly get into quite esoteric direction.

If I have time I can try reading bit more about what kinds of escapes certain CSV dialects use, if any.
