### ISSUE TITLE
Mapping not working when header is enclosed in double quotes

### ISSUE THREAD

**Issue by pramodbindal** [FasterXML/jackson-dataformat-csv#152]
Hi,
I have a CSV  as below

"NAME", "EMAIL"
"Test", "test@email.com"

My code is as below

CsvMapper csvMapper = new CsvMapper();
CsvSchema schema = CsvSchema.emptySchema().withHeader().withQuoteChar(QUOTE);
ObjectReader oReader = csvMapper.readerFor(beanClass).with(schema);
MappingIterator<T> mi = oReader.readValues(inputStream)

now mi.next() is return the object with all fields as null.

**Comment by cowtowncoder** [comment]
Code looks good in general but it'd be good to know two things:

1. Which Jackson version you are using (if not latest patch, make sure you are using latest patch for minor version!)
2. What does target class look like

**Comment by pramodbindal** [comment]
this is working fine on latest version.
Thanks
