### ISSUE TITLE
 Jdbc ResultSet to CSV

### ISSUE THREAD

**Issue by pramodbindal** [FasterXML/jackson-dataformat-csv#154]
Hi,
Do you support Jdbc ResultSet to CSV generation ?
If yes then please share me the doc

**Comment by cowtowncoder** [comment]
No, CSV is read from CSV content, and `ResultSet` is a POJO so there is no direct source setting.

In future, please use mailing lists for usage questions:

https://groups.google.com/forum/#!forum/jackson-user

as issue trackers are for filing issues.

**Comment by pramodbindal** [comment]
Thanks.
I did something line this.

```
public static void convertToCsv(ResultSet rs, String fileName) throws SQLException, IOException {
        File file = new File(fileName);
        FileOutputStream fos = new FileOutputStream(file);
        BufferedWriter br = new BufferedWriter(new OutputStreamWriter(fos));
        ResultSetMetaData meta = rs.getMetaData();
        int numberOfColumns = meta.getColumnCount();
        StringJoiner stringJoiner = new StringJoiner(",");
        for (int i = 1; i < numberOfColumns + 1; i++) {
            stringJoiner.add(clean(meta.getColumnName(i)));
        }
        br.write(stringJoiner.toString());
        br.newLine();
        while (rs.next()) {
            stringJoiner = new StringJoiner(",");
            for (int i = 1; i < numberOfColumns + 1; i++) {
                stringJoiner.add(clean(rs.getString(i)));
            }
            br.write(stringJoiner.toString());
            br.newLine();
        }
        br.close();
    }
```

**Comment by pramodbindal** [comment]
Currently this is very raw format. But you can add features of Value formatting based on the Column DataType and Some custom format suppplied

**Comment by cowtowncoder** [comment]
@pramodbindal FWTW I have thought about maybe considering some sort of support for `ResultSet` since it is common source for input. I don't think it necessary belongs in CSV module (it has similarities, but it's really not related conceptually), but not sure if it'd be separate datatype module or just extension of `jackson-databind`. I guess it depends on scope; bigger scope more likely separate module makes sense.

**Comment by pramodbindal** [comment]
Thanks
