### ISSUE TITLE
Map support in POJO member 

### ISSUE THREAD

**Issue by shaon002** [FasterXML/jackson-dataformat-csv#25]
My initial purpose was to serialize the following POJO class

public class Application {
String name;
String description; 
// failed to serialize this member
HashMap <String, String> customAttr;
....
}

I came to know this is not supported at this moment, any ETA when it will be.

**Comment by cowtowncoder** [comment]
No current work, or ideas what should be done, so will close for now. May be re-filed at new repo at:

https://github.com/FasterXML/jackson-dataformats-text
