### ISSUE TITLE
Is it possible to wrap the jackson-dataformat-csv artifact to a jackson-jaxrs-cvs-provider one?

### ISSUE THREAD

**Issue by ffbit** [FasterXML/jackson-dataformat-csv#35]
It'd be good to have the jackson-jaxrs-cvs-provider derived from this artifact.
Thanks.

**Comment by TuomasKiviaho** [comment]
@cowtowncoder I crafted my own which was mostly just copy/pasting of the json-provider and overwriting of the ``readFrom``(/``writeTo``) method(s) using POJO approach for the schema. ``readValue`` works fine for ``SimpleType``, but it seems that ``MappingIterator`` via ``readValues`` is currently the only option for ``CollectionLike/ArrayType``. Could there be a detection in ``schemaFor(JavaType)`` for this and a corresponding CsvParser.Feature (for instance) that enables outputting of POJOs inside of collections/arrays(/maps?). This would suit JAX-RS better than the Jackson specific ``MappingIterator``

**Comment by cowtowncoder** [comment]
Hmmh. Interesting thought. `readValue()` should work just fine for arrays/`Collection`s, but handling of schema would need special care. And it would, I think, make sense to add special handling for these types in `CsvMapper` -- there is no other way to create a schema for such types.

I think I need to file a separate issue for that.

**Comment by cowtowncoder** [comment]
Moved: https://github.com/FasterXML/jackson-dataformats-text/issues/16
