### ISSUE TITLE
Add a feature in `CsvSchema` to allow definition of ordering

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-csv#42]
(note: cleaved off of #40)

---

Currently the only way to specify ordering of columns with `CsvSchema` is to either use `@JsonPropertyOrder` annotation in POJO class, or to manually build schema.
But there is no way to indicate alternate ordering, explicit (by listing possibly partial list of columns) or otherwise (defining a strategy to use for sorting).
But there should be a way: for example, by having method(s) in `CsvSchema` to allow re-ordering of columns.

**Comment by ShijunK** [comment]
It seems the implementation only sorts the columns in headers, not actual values. 

I have a test for 2.6.3

````
   public void testValueReorderByName() throws Exception
    {
        CsvMapper mapper = mapperForCsv();
        CsvSchema schema = mapper.schemaFor(Mixed.class);
        assertEquals(aposToQuotes("['a','b','c','d']"), schema.getColumnDesc());
        schema = schema.sortedBy("b", "c");
        assertEquals(aposToQuotes("['b','c','a','d']"), schema.getColumnDesc());

        Mixed value = new Mixed();
        value.a = 1;
        value.b = 2;
        value.c = 3;
        value.d = 4;

        schema = schema.withHeader();
        String outputString = mapper.writer(schema).writeValueAsString(Arrays.asList(value));
        assertThat(outputString, is(equalTo("b,c,a,d\n2,3,1,4\n")));

        _verifyLinks(schema);
    }
````

test output:
````
java.lang.AssertionError: 
Expected: is "b,c,a,d\n2,3,1,4\n"
     but: was "b,c,a,d\n1,2,3,4\n"
````
