### ISSUE TITLE
When write array to file it's write with "["

### ISSUE THREAD

**Issue by ar-g** [FasterXML/jackson-dataformat-csv#44]
I used it like this:
mapper.enable(CsvParser.Feature.WRAP_AS_ARRAY);
String[][] s = ...
mapper.writeValue(file, s);
It wrote with 
[,,]
[,,]
But when I writeValueAsString() it's ok

**Comment by cowtowncoder** [comment]
I am not sure what this means. May be reopened/refiled with a unit test.
