### ISSUE TITLE
"csv" files with UTF-8 with BOM encoding are returning the first column with quotes

### ISSUE THREAD

**Issue by andrealexandre** [FasterXML/jackson-dataformat-csv#47]
Take the csv header example:

"ID", "Name", "Age
(...)

When the file is encoded UTF-8 with BOM, the CsvReader will return the first column came with the following string: ""ID"".

**Comment by andrealexandre** [comment]
I can only share an example file, but I tested it and I found the same
problem with this file.

I found that you can replicate this by editing a .csv file with Notepad++
and convert to encoding to UTF-8.

I hope it was helpful.

2014-07-08 21:02 GMT+01:00 Tatu Saloranta notifications@github.com:

> I don't offer a way to specify encoding because it's safer to just require
> use of java.io.Reader, if encoding is already known. With CSV things are
> more difficult wrt auto-detection (since there's no well-known start
> sequence), but it should be relatively easy to fix BOM handling. It's just
> not properly tested I think.
> 
> So: I just want to know exact BOM bytes in use -- there are kinds of
> broken content where what looks like a BOM is not valid one.
> 
> Is it possible to share the File, or at least first couple of bytes? It
> should be easy enough to figure out the problem with that.
> 
> Thanks again for reporting the problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FasterXML/jackson-dataformat-csv/issues/47#issuecomment-48392620
> .

## 

Best regards,
André Alexandre

**Comment by tom999** [comment]
Thanx helped me out, after first columns was always null.
