### ISSUE TITLE
Add a way to specify "null value" (String) for `CsvGenerator` to use when writing `null`s

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-csv#53]
Looks like many CSV processors allow use of specific placeholder to use instead of Java `null`, instead of empty String. We should allow that as well; and with 2.5, may be able to configure it nicely on per-call basis via `ObjectWriter` as well.

**Comment by flappingeagle** [comment]
nice, we will use this to serialize null-values as "(null)" like the DBVisualizer-App does it ;)

It would be nice if this configuration also works for deserialization. For example, the following call would not recognize this configuration and will return the String "(null)   " in the resulting map while parsing a csv-file:

            Map<String, String> line = csvReader.nextValue();

but its also no problem for us to post-process this ourselves...

**Comment by cowtowncoder** [comment]
Good idea; I agree in that this would make sense. Could you file a separate issue so this is easier to track?
