### ISSUE TITLE
Add a `CsvSchema` option to allow skipping empty rows

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-csv#59]
Looks like a commonly supported option with CSV (family of formats) is to allow skipping of empty rows; that is, ones that only contain white-space.

**Comment by jedvardsson** [comment]
+1

**Comment by flappingeagle** [comment]
+1

**Comment by cowtowncoder** [comment]
Moved: https://github.com/FasterXML/jackson-dataformats-text/issues/15
