### ISSUE TITLE
How to ignore some properties?

### ISSUE THREAD

**Issue by wangcee** [FasterXML/jackson-dataformat-csv#63]
e.g. 
```Java
public class UserEntity {
	private String name;
	private int age;
	private String password;
	
}
```

i don't like to export "password" 
how to ignore it ?

**Comment by cowtowncoder** [comment]
The usual Jackson ways; `@JsonIgnore`, use of JSON Views (`@JsonView`) or JSON Filters.
Despite naming, they work for other formats too.

In future, please use mailing list. Issue trackers are for reporting issues, not for user questions.
