### ISSUE TITLE
Allow no quoting of columns

### ISSUE THREAD

**Issue by jonchase** [FasterXML/jackson-dataformat-csv#67]
For compatibility with a legacy TSV log format we support internally, I need to be able to configure CsvSchema to NOT output quotes around columns (even when it really would be better if it did).  

I've implemented this by adding a `withoutQuoteChar()` method to CsvSchema:

```java
CsvSchema schema = mapper.schemaFor(FiveMinuteUser.class).withoutQuoteChar();
```

To do so, I've essentially copied `withoutEscapeChar()` and changed `quoteChar` from a `char` to an `int` so that it can hold the -1 flag:

```java
    public CsvSchema withoutQuoteChar() {
        return (_quoteChar == -1) ? this
                : new CsvSchema(_columns, _useHeader, _skipFirstDataRow,
                        _columnSeparator, -1, _escapeChar, _lineSeparator, _columnsByName);
    }
```

I'll try to get the fork pushed shortly, though I had to make it against an older version (2.3.4), so I'm not sure if it'd need updated for 2.5.0.

**Comment by jonchase** [comment]
https://github.com/jonchase/jackson-dataformat-csv/commit/c1665ea9af07ac4e2d2ec972eb929a8b859984d6

Let me know if I should do a PR, etc.

**Comment by cowtowncoder** [comment]
There is already `withoutQuoteChar()`, added in 2.4. Would this work as is? This is assuming functionality works the way you want.

As to modifying 2.3: unfortunately API can not be changed in patch releases, so I think upgrade is the best way; except if you want to have a locally modified and built version.

**Comment by jonchase** [comment]
`withoutQuoteChar()` sounds perfect.  Unfortunately, I may be stuck on 2.3.4 - if so, I'll just stick with my locally built version for now.  Thanks!

**Comment by cowtowncoder** [comment]
Sounds good.
