### ISSUE TITLE
Recognize the configured "null value" (String) also in reader-infrastructure.

### ISSUE THREAD

**Issue by flappingeagle** [FasterXML/jackson-dataformat-csv#72]
In issue #53 a way to specify a configured "null value" (String) in CsvSchema has been implemented and can be used like:

```java
CsvSchema schema = CsvSchema.builder()
    .setNullValue("n/a")
    .build();
```

While this new property is already recognized by the Writer-Infrastructure it should also be recognized by the Reader-Infrastructure for deserialization to Java-Null-Values.

**Comment by seglo** [comment]
I was disappointed to find out the reader doesn't respect this as well.  Right now I have no way of determining whether or not a String is a null or empty value.
