### ISSUE TITLE
Improve error message for non-UTF8 content

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-csv#73]
(based on http://stackoverflow.com/questions/29369602/charconversionexception-in-parsing-csv-file-using-jacksons-csv-data-format-modu/29401537)

When encountering an issue with non-UTF-8 content, it would make sense to suggest that a likely cause is the use non-UTF-8 encoding such as ISO-8859-1. Especially if character would be printable character.
But even if not, current error message is rather cryptic and should be improved.

**Comment by ZioberMichal** [comment]
Hi @cowtowncoder,
I think this is a good idea to improve this message. My propositions:
1.
```java
throw new CharConversionException("Invalid UTF-8 start byte 0x"+Integer.toHexString(mask)
        +" (at char #"+charPos+", byte #"+bytePos+"). Use other encoding than default.");
```
2.
```java
throw new CharConversionException("Invalid UTF-8 start byte 0x"+Integer.toHexString(mask)
        +" (at char #"+charPos+", byte #"+bytePos+"). Check file encoding.");
```
3.
```java
throw new CharConversionException("Invalid UTF-8 start byte 0x"+Integer.toHexString(mask)
        +" (at char #"+charPos+", byte #"+bytePos+"). Try to use other file encoding.");
```

`UTF8Reader.reportInvalidOther` method could be vulnerable on the same problem. Do you think we should change exception message in for this method as well?

**Comment by cowtowncoder** [comment]
Was about to suggest adding that exception in `jackson-core`, until I realized this is already in JDK (since 1.1). I agree that its use would make sense, and make a quick change.
I think I like option (2) the most; I can go with that for 2.6 (finalized any day now).

**Comment by ZioberMichal** [comment]
That's happens when you're working on so many different libraries ;)

Looks much better now.

**Comment by cowtowncoder** [comment]
I think improvement was checked in, closing.
