### ISSUE TITLE
Unexpected output with arrays starting with a null/empty element

### ISSUE THREAD

**Issue by cheseaux** [FasterXML/jackson-dataformat-csv#90]
Take this small example :

```
public class MyPojo {

    public String[] getVal1() {
	    return new String[]{"", "foo"};
    }

    public String[] getVal2() {
	    return new String[]{null, "bar"};
    }
    
    public String[] getVal3() {
	    return new String[]{"baz",null};
    }

    public static void main(String[] args) throws JsonProcessingException {
	    MyPojo jacksonBug = new MyPojo();
	    CsvMapper mapper = new CsvMapper();
	    String csvContent = mapper.writer(mapper.schemaFor(MyPojo.class).withHeader()).writeValueAsString(jacksonBug);
	    System.out.println(csvContent);
    }

}
```

Output is : 
>val1,val2,val3
>foo,bar,baz;

But should be : 
>val1,val2,val3
>;foo,;bar,baz;

**Comment by cowtowncoder** [comment]
Which version?

**Comment by cheseaux** [comment]
Sorry, forgot to mention it : v 2.6.1 but was also present in 2.5

**Comment by cheseaux** [comment]
Ok, I've found where the bug is.

In *CsvGenerator.java*, the two methods *_addToArray* inserts the array separator character if at least one character was already appended to *_arrayContents*. But when the first element of the array is empty or null, then this condition will return false and no array separator character will be appended.

I suggest replacing these conditions as follows :

    protected void _addToArray(String value) {
        if (_arrayContents.length() > 1 || (_arrayContents.length() == 0 && value.length() == 0)) {
            _arrayContents.append((char) _arraySeparator);
        }
        _arrayContents.append(value);
    }
    
    protected void _addToArray(char[] value) {
        if (_arrayContents.length() > 1 || (_arrayContents.length() == 0 && value.length == 0)) {
            _arrayContents.append((char) _arraySeparator);
        }
        _arrayContents.append(value);
    }

I haven't test it thoroughly but in my previous test case this solves the problem.

**Comment by cheseaux** [comment]
Ok, I've found where the bug is.

In CsvGenerator.java, the two methods _addToArray inserts the array separator character if at least one character was already appended to _arrayContents :+1: 

    protected void _addToArray(String value) {
        if (_arrayContents.length() > 0) {
            _arrayContents.append((char) _arraySeparator);
        }
        _arrayContents.append(value);
    }
    
    protected void _addToArray(char[] value) {
        if (_arrayContents.length() > 0) {
            _arrayContents.append((char) _arraySeparator);
        }
        _arrayContents.append(value);
    }

But when the first element of the array is empty or null, then this condition will return false and no array separator character will be appended.
