### ISSUE TITLE
Ensure that "too many columns" is recoverable

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-dataformat-csv#91]
(note: based on http://stackoverflow.com/questions/32752245/skip-malformed-csv-row)

Looks like recovery does not work for case where there are extra column values, compared to schema information. It should work to the degree that while an exception is thrown for specific line, it should be possible to continue reading remaining lines.

**Comment by cowtowncoder** [comment]
Ok, yes, I can reproduce the issue: recovery process hits a snag at low level, and this needs to be resolved.

**Comment by cowtowncoder** [comment]
Looks like a simple check to skip column access works well, fixed for 2.6.3.

**Comment by sergey-ostapenko** [comment]
Don't sure if it's connected error, but if we have malformed row with unclosed quote in middle of document, we can't recover from error too. 
We get this error firs:
```Unexpected character ('A' (code 65)): Expected separator ('"' (code 34)) or end-of-line```
And after ignoring it and trying to proceed reading file we get following exception: 
```Too many entries: expected at most 11 (value #11 (5 chars) "29.90")```
It seems that `CsvParser` don't reset column count in this case. If error occurred on second column, then `CsvParser` will tread first column of next record as third column. 

Can you please check this case too?

**Comment by cowtowncoder** [comment]
Ok, I'll see what I can do there. Should be possible to try to recover there too, even if it is bit more fundamental problem.

**Comment by cowtowncoder** [comment]
Actually I think fix should work for that too. For additional failures will need a unit test.

**Comment by sergey-ostapenko** [comment]
I checked it on current master version (2.7.0-SNAPSHOT), and error still occur.
You can reproduce this error with following unit test:
```java
public class ParseUnclosedQuoteTest extends ModuleTestBase {

  String toParse =
      "\"value1\",\"value2\",\"value3\"\n" +
      "\"value4\",\"value5\",\"value6\n" +
      "\"value7\",\"value8\",\"value9\"\n";

  @JsonPropertyOrder({"s1", "s2", "s3"})
  protected static class ThreeString {
    public String s1, s2, s3;
  }

  // Additional test For #91: should skip only line with error and do not fail on next line
  public void testUnclosedQuotes() throws Exception
  {
    CsvMapper mapper = mapperForCsv();
    CsvSchema schema = mapper.schemaFor(ThreeString.class);
    MappingIterator<ThreeString> it = mapper.reader(schema).forType(ThreeString.class).readValues(toParse);
    List<ThreeString> result = new ArrayList<>();

    while (it.hasNextValue()) {
      try {
        ThreeString entry = it.nextValue();
        result.add(entry);
      } catch (IOException e) {
      }
    }

    // first and third strings should be parsed correctly
    assertEquals(result.size(), 2);

    assertEquals("value1", result.get(0).s1);
    assertEquals("value2", result.get(0).s2);
    assertEquals("value3", result.get(0).s3);

    assertEquals("value7", result.get(1).s1);
    assertEquals("value8", result.get(1).s2);
    assertEquals("value9", result.get(1).s3);
  }
}
```

**Comment by cowtowncoder** [comment]
@sergey-ostapenko Thank you for verifying behavior and providing test case. I will see what is happening.

**Comment by cowtowncoder** [comment]
Ok, yes. There is another case that needs to lead to low-level recovery; just checked in.

Note however that the test needs to be modified slightly because the missing quote is only found on third row, not second: it is legal to have a linefeed within quoted content (as per CSV definition), so the problem is found when what is taken as closing quote (but in reality is meant to be the opening quote of "value4") is followed not by separator or space, but by `v`. Exception is thrown as expected and recovery must then discard the remaining of that row.

With the fix and modifications to verification test now passes against 2.6.3.

Since the way these fixes have to be done are quite specific, it is likely that there are many other edge cases. Error recovery is not exact business. But we can improve it step by step.
